export const FETCH_CARLIST = 'FETCH_CARLIST';
export const FETCH_CARLIST_SUCCESS = 'FETCH_CARLIST_SUCCESS';
export const FETCH_CARLIST_FAILURE = 'FETCH_CARLIST_FAILURE';

export const FETCH_MANUFACTURE = 'FETCH_CARLIST';
export const FETCH_MANUFACTURE_SUCCESS = 'FETCH_MANUFACTURE_SUCCESS';
export const FETCH_MANUFACTURE_FAILURE = 'FETCH_MANUFACTURE_FAILURE';

export const FETCH_COLORLIST = 'FETCH_COLORLIST';
export const FETCH_COLORLIST_SUCCESS = 'FETCH_COLORLIST_SUCCESS';
export const FETCH_COLORLIST_FAILURE = 'FETCH_COLORLIST_FAILURE';


export const SET_PAGE_NO = 'SET_PAGE_NO';
export const SET_SORT_ORDER = 'SET_SORT_ORDER';

export const SET_MANUFACTURER = 'SET_MANUFACTURER';
export const SET_COLOR = 'SET_COLOR';